### ISSUE TITLE
thrift_sasl-0.3.0-py3.6.egg/thrift_sasl/__init__.py", line 67, in open AttributeError: 'TSocket' object has no attribute 'is_open'

### ISSUE THREAD

**Issue by DiwanshuShekhar** [dropbox/PyHive#194] opened 2018-03-12 22:38 UTC
thrift==0.11.0
thrift-sasl==0.3.0
thriftpy==0.3.9
PyHive==0.5.1

OS - Red Hat Enterprise Linux Server release 6.5
Python 3.6

**Comment by liujiao1** [comment] 2018-03-13 06:22
I have same bug.
python3.6
install setup:
git clone https://github.com/dropbox/PyHive.git
cd PyHive
pip3 install -r dev_requirements.txt 

error:
# python3
Python 3.6.4 (default, Mar 13 2018, 13:35:52) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyhive import hive
>>> from TCLIService.ttypes import TOperationState
>>> cursor = hive.connect('172.16.30.39').cursor()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/python3.6/lib/python3.6/site-packages/pyhive/hive.py", line 64, in connect
    return Connection(*args, **kwargs)
  File "/usr/local/python3.6/lib/python3.6/site-packages/pyhive/hive.py", line 162, in __init__
    self._transport.open()
  File "/opt/thrift_sasl/thrift_sasl/__init__.py", line 67, in open
    if not self._trans.is_open():
AttributeError: 'TSocket' object has no attribute 'is_open'

**Comment by jingw** [comment] 2018-03-25 04:21
Thanks for reporting. This is a dupe of #192.

Unfortunately, it's code not in my direct control, and I don't currently have time to spend on this.

**Closed by jingw** 2018-03-25 04:21 UTC
